### PR TITLE
feat: cors middleware, preflight/content type

### PR DESCRIPTION
**Pull request by zachferland**
replaces with cors middleware library, handles complex req, post with content application/json not supported by only allow origin, this supports those headers and preflight reqs

### CODE REVIEW

**Comment by zachferland** [comment]
also want to get in release, to easily deploy and use tmrrw

someone will have show me how we are making releases here!

**Review by simonovic86 — APPROVED** [review]

**Comment by simonovic86** [comment]
> also want to get in release, to easily deploy and use tmrrw
> 
> someone will have show me how we are making releases here

you can use these [steps](https://github.com/ceramicnetwork/js-ceramic/blob/develop/README.md#creating-a-release) for now 😊

**Comment by zachferland** [comment]
thanks @simonovic86 

ah nice, so can push out 'prereleases' pretty often, going to try that after

**Comment by simonovic86** [comment]
np! @zachferland

**Pull request merged**
