### PR TITLE
chore: Docker image builds again

### PR DESCRIPTION
**Pull request by ukstv**
Or at least supposed to do so.

### CODE REVIEW

**Comment by valmack** [comment]
Still seeing error when trying to build locally.. 🤔 

```
> root@ build /js-ceramic
> lerna run build

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 16 packages: "npm run build"
lerna ERR! npm run build exited 2 in 'key-did-resolver'
lerna ERR! npm run build stdout:

> key-did-resolver@0.2.5-rc.0 prebuild /js-ceramic/packages/key-did-resolver
> npm run clean


> key-did-resolver@0.2.5-rc.0 clean /js-ceramic/packages/key-did-resolver
> rm -rf ./lib


> key-did-resolver@0.2.5-rc.0 build /js-ceramic/packages/key-did-resolver
> ../../node_modules/.bin/tsc -p tsconfig.json

src/ed25519.ts(1,22): error TS2307: Cannot find module 'uint8arrays' or its corresponding type declarations.
src/secp256k1.ts(1,22): error TS2307: Cannot find module 'uint8arrays' or its corresponding type declarations.

lerna ERR! npm run build stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! key-did-resolver@0.2.5-rc.0 build: `../../node_modules/.bin/tsc -p tsconfig.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the key-did-resolver@0.2.5-rc.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-04T14_29_54_518Z-debug.log

lerna ERR! npm run build exited 2 in 'key-did-resolver'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! root@ build: `lerna run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the root@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-04T14_29_54_564Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 2
```

**Comment by ukstv** [comment]
Even CircleCI makes it build. You sure you have nothing else to pollute the setup? `npm clean` maybe before the build? @valmack

**Comment by oed** [comment]
@valmack what command do you use to build the dockerfile locally?

**Comment by ukstv** [comment]
CircleCI fails to build racing code here. So much fun.

**Review by oed — APPROVED** [review]

**Pull request merged**
