### PR TITLE
feat: Do not depend on bigint-mod-arith

### PR DESCRIPTION
**Pull request by ukstv**
Unless it can be really used as ES module.

Copied the relevant code inside.

Relevant issue: https://github.com/juanelas/bigint-mod-arith/pull/6

### CODE REVIEW

**Comment by ukstv** [comment]
CC @smrz2001

**Review by oed — APPROVED** [review]
ugh, let's monitor upsteam and hope your fix get's merged.

**Comment by smrz2001** [comment]
In case something like this is needed again in the future, wanted to add another option. The followings command will pull in a fork/branch from GitHub directly into the project dependencies. This works for all public repositories and can be an alternative to copying code. Can also use a tag or commit hash in place of the branch (or leave the `#...` part out entirely to use the default branch).
```
npm install "username/repo#branch" --save
```
OR
```
yarn add "username/repo#branch"
```
e.g,
```
npm install "ukstv/bigint-mod-arith#master" --save
```

**Comment by ukstv** [comment]
Thanks! @smrz2001 AFAIK, it would require built artefacts to be stored in the repo, which is not quite nice if the repo uses TypeScript.

**Comment by smrz2001** [comment]
> Thanks! @smrz2001 AFAIK, it would require built artefacts to be stored in the repo, which is not quite nice if the repo uses TypeScript.

Ahh, gotcha, @ukstv 👍🏼

**Pull request merged**
