### PR TITLE
feat(core): Remove chainId from document metadata and stop enforcing of chainId when applying records

### PR DESCRIPTION
**Pull request by stbrody**

### CODE REVIEW

**Comment by stbrody** [comment]
FYI @PaulLeCam

**Review by oed — APPROVED** [review]
Lgtm.
Also seem like we never implemented the chainid logic for `caip10-link`s 🤔

**Comment by stbrody** [comment]
> Also seem like we never implemented the chainid logic for `caip10-link`s

@oed what do you mean?  This PR includes changes to `caip10-link-doctype.ts` and `caip10-link-doctype-handler.ts` that is removing the chainId logic that was previously added...

**Comment by oed** [comment]
Err, seems like I somehow missed that 😵

**Pull request merged**
