### PR TITLE
fix: sleep if loop duration is a special 0

### PR DESCRIPTION
**Pull request by ukstv**

### CODE REVIEW

**Comment by stbrody** [comment]
hmm, can you explain the motivation behind this change?  The `minLoopDurationMs` isn't configurable currently and is hard-coded to 1 minute, so I don't think it could ever be 0 so this new case will never be hit.

**Comment by ukstv** [comment]
> hmm, can you explain the motivation behind this change? The `minLoopDurationMs` isn't configurable currently and is hard-coded to 1 minute, so I don't think it could ever be 0 so this new case will never be hit.

https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/stream-tests/src/create-ceramic.ts#L27 Really?

**Comment by ukstv** [comment]
On a serious note, pinged you on Linear.

**Comment by stbrody** [comment]
ah whoops, I was only thinking about in production code, not test code.  Good catch, makes sense.

**Comment by ukstv** [comment]
Yahoo!

**Pull request merged**
