### PR TITLE
chore: use cross-platform rimraf

### PR DESCRIPTION
**Pull request by ukstv**
So that it can work on windows.

### CODE REVIEW

**Comment by smrz2001** [comment]
🚢 🚀

**Comment by ukstv** [comment]
@smrz2001 does it really work for you this way? I am worried, if `rimraf` is not installed globally, the main command would fail right away. There is no `rimraf` executable in this case.

**Comment by smrz2001** [comment]
Ahh, I see. It does not work without global rimraf but is that an issue? Without removing node_modules we won't be able to get a clean install.

**Comment by smrz2001** [comment]
But let's discuss because I do see your point.

**Comment by ukstv** [comment]
Maybe we could `rimraf ./node_modules` the last thing though. It should first load `rimraf` into memory, so no files are required.

**Comment by smrz2001** [comment]
I have another idea but it's a bit ugly. We could replace the top-level rimraf with (rm -rf node_modules || true) && (del node_modules || true).

**Comment by ukstv** [comment]
I like it, really, but I have no idea how to avoid messages like `sh: del: command not found` in a cross-platform fashion.

**Comment by smrz2001** [comment]
Made some updates to my PR @ukstv. Adding `npx` before `rimraf` will download and cache `rimraf` if it is not already installed.

Please check.

**Pull request merged**
