### PR TITLE
feat: Use old caip format for proofs

### PR DESCRIPTION
**Pull request by ukstv**
Apparently, found a bug in v2 client communicating with v1 daemon. v2 client should use old CAIP format string in proofs.

### CODE REVIEW

**Comment by oed** [comment]
Why is this necessary?

Anyway I don't think this matters much as I imagine we will update caip10-links to support CACAOs created by the pkh DID correlating to the caip10 in the *controller*. So new commits will be JWS :)

**Review by stbrody — COMMENTED** [review]
ooh good catch!  Can we add some testing?

**Comment by stbrody** [comment]
> ooh good catch! Can we add some testing?

looks like there actually was tests already, they just need to be updated

**Comment by ukstv** [comment]
> > ooh good catch! Can we add some testing?
> 
> looks like there actually was tests already, they just need to be updated

yup. and they rightfully fail now.

**Comment by oed** [comment]
> I didn't follow this. Don't we need to preserve the existing format for backwards compatibility? 

Yes ofc! 

My first comment was more regarding that I thought the proof verifier should support both old and new format!

**Comment by stbrody** [comment]
> My first comment was more regarding that I thought the proof verifier should support both old and new format!

Right, so here in blockchain-utils-linking we want to always be *creating* the proofs in the old format for backwards compatibility, at least for the time being.  Then in blockchain-utils-validation we could make it support both old and new formats.  Then after support for both formats has been out long enough that we think most Ceramic nodes have updated and have that support, then we can start producing proofs in the new format.

**Comment by oed** [comment]
> Right, so here in blockchain-utils-linking we want to always be creating the proofs in the old format for backwards compatibility, at least for the time being. Then in blockchain-utils-validation we could make it support both old and new formats. Then after support for both formats has been out long enough that we think most Ceramic nodes have updated and have that support, then we can start producing proofs in the new format.

Makes sense! Good catch indeed. 

My other point was that we likely wouldn't care about changing this to the new caip10 format as we would likely phase in support for new JWS + CACAO proofs.

**Comment by ukstv** [comment]
Changed all of the blockchains to use old caip for proofs :/

**Comment by PaulLeCam** [comment]
cc @zachferland this might affect the changes you made in 3ID Connect

**Review by stbrody — APPROVED** [review]
this LGTM but I'd like @zachferland to take a look and confirm that 3id-connect is prepared for this before we merge

**Comment by zachferland** [comment]
yeah ran into this today as well, yeah definitely need this, and looks good

**Review by zachferland — APPROVED** [review]

**Comment by stbrody** [comment]
does this need to be backported to the V1 branch and released as a hotfix to the current Ceramic version? @zachferland @ukstv

**Comment by ukstv** [comment]
> does this need to be backported to the V1 branch and released as a hotfix to the current Ceramic version? @zachferland @ukstv 

AFAIK v1 uses old caip everywhere.

**Pull request merged**
