### PR TITLE
chore: bump ipfs

### LINKED ISSUE #1466: Can not install 1.0.5 - missing dep ipfs-repo
Someone reported this in Discord and I was able to repro on a clean install

```
npm install -g @ceramicnetwork/cli
```

```
~|⇒ ceramic daemon
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'ipfs-core'
Require stack:
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/ipfs-daemon.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/index.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/build-ipfs-connection.util.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-cli-utils.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/bin/ceramic.js
- /.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/bin/ceramic.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/ipfs-daemon.js:7:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/ipfs-daemon.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/ipfs-daemon/lib/index.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/build-ipfs-connection.util.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-daemon.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/ceramic-cli-utils.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/lib/bin/ceramic.js',
    '/.nvm/versions/node/v14.13.1/lib/node_modules/@ceramicnetwork/cli/bin/ceramic.js'
  ]
}
```

### PR DESCRIPTION
**Pull request by oed**
Fix #1466

### CODE REVIEW

**Review by stbrody — APPROVED** [review]
LGTM

**Comment by stbrody** [comment]
Can we remove this node-fetch pin now that it got properly released? https://github.com/ceramicnetwork/js-ceramic/blob/e396db2120d536f6fde101095fc97b470a3e3267/package.json#L48-L50

**Comment by oed** [comment]
> Can we remove this node-fetch pin now that it got properly released? 

Afaik *node-fetch* has not been released.

**Comment by stbrody** [comment]
> > Can we remove this node-fetch pin now that it got properly released?
> 
> Afaik _node-fetch_ has not been released.

Whoops you're right, I misinterpreted a message from achingbrain

**Review by stbrody — APPROVED** [review]
lgtm

**Pull request merged**
