### PR TITLE
feat: allow any ipfs url to be passed

### PR DESCRIPTION
**Pull request by valmack**
Same as #524 except this accommodates our new package names.

### CODE REVIEW

**Comment by valmack** [comment]
Seems builds are failing from a different commit?

**Comment by simonovic86** [comment]
> Seems builds are failing from a different commit?

@valmack That should be fixed with the latest `develop`. Feel free to rerun CI.

**Review by simonovic86 — COMMENTED** [review]
@valmack I guess we can close this PR since the hotfix PR will be pulled back to `develop`, right?

**Comment by valmack** [comment]
@simonovic86 but the docker files need to be different because of the package names

**Comment by valmack** [comment]
Closing in favor of https://github.com/ceramicnetwork/js-ceramic/pull/526

**Pull request closed without merging**
