### PR TITLE
[Hotfix] - Remove colors

### PR DESCRIPTION
**Pull request by Sterahi**
Remove colors added in from #1985

### CODE REVIEW

**Comment by ukstv** [comment]
@Sterahi Hey, should we just close it now?

**Comment by Sterahi** [comment]
@ukstv If the most recent version of js-ceramic includes the depreciation notice we can close it, but until that gets added/closed I'd rather keep this live.

**Comment by ukstv** [comment]
This is the latest `develop`:

Screenshot 2022-03-02 at 15 14 13

I believe, it can be closed.

**Comment by Sterahi** [comment]
Thanks Sergey!

**Comment by ukstv** [comment]
Whoops. Have not refreshed the page.

**Pull request closed without merging**
