### PR TITLE
IPFS 0.50.0

### PR DESCRIPTION
**Pull request by simonovic86**
- bump `IPFS` version
- bump `IdentityWallet` version
- fix and adapt failing tests

### CODE REVIEW

**Review by oed — APPROVED** [review]
lgtm

**Review by PaulLeCam — APPROVED** [review]
Nice to get these versions in sync!

**Comment by oed** [comment]
I guess we could also remove the type declarations for ipfs?

**Comment by simonovic86** [comment]
> I guess we could also remove the type declarations for ipfs?

yep, I'll do that in the next PR 👍

**Pull request merged**
