### PR TITLE
feat(cli): Remove support for did:safe and did:nft

### PR DESCRIPTION
**Pull request by stbrody**
They've always been marked as experimental, have never been safe to use in production, we aren't planning on investing more work into supporting them, and even if we wanted to we aren't actually sure what the path towards making them safe would even be.

CC @ukstv @3avi @LFeld

### CODE REVIEW

**Comment by ukstv** [comment]
Sad, but makes sense.

**Comment by oed** [comment]
Not sure it really make sense to remove them from the code base? Can't we keep them as long as we are clear about them being experimental?

**Comment by stbrody** [comment]
@oed as long as we have them around we will continue to get questions about them, and people will continue to want to use them in production.  This will cause a constant low-level drag on our team to be always having to answer these questions and explain why these methods are not supported in Ceramic.
I really don't think it makes sense to keep around a feature that isn't safe to use and that we have no plans now or ever to fix.  It just increases the complexity and surface area of Ceramic for something that we don't even want to support.

**Comment by qbig** [comment]
@stbrody @oed Could you elaborate how they are not secure?

**Comment by 3avi** [comment]
> @stbrody @oed Could you elaborate how they are not secure?

hey Liang, can you ask this question on the forum https://forum.ceramic.network/ -- I'll look for your question there

**Comment by stbrody** [comment]
closing in favor of https://github.com/ceramicnetwork/js-ceramic/pull/3021

**Pull request closed without merging**
