### PR TITLE
IPFS bump

### PR DESCRIPTION
**Pull request by simonovic86**
- bump IPFS dependencies
- remove hardcoded dependency `libp2p-pubsub`

### CODE REVIEW

**Review by PaulLeCam — APPROVED** [review]

**Comment by oed** [comment]
Nice, no need for the specific jest environment?

**Comment by simonovic86** [comment]
> Nice, no need for the specific jest environment?

Good point, I'll check. Maybe it's fixed now.

**Comment by simonovic86** [comment]
> > Nice, no need for the specific jest environment?
> 
> Good point, I'll check. Maybe it's fixed now.

@oed we still need the specific jest env

**Comment by oed** [comment]
oh, I meant the `jest-environment-uint8array` but it doesn't seem like it.

**Review by oed — APPROVED** [review]

**Pull request merged**
