### PR TITLE
chore(stream-tests): Test that you cannot index a non-model streamid

### PR DESCRIPTION
**Pull request by stbrody**

### CODE REVIEW

**Comment by smrz2001** [comment]
Hey @stbrody, IIUC, this test isn't needed since we're already testing what it's doing, is that right?

**Comment by stbrody** [comment]
@smrz2001 I'm sorry, I don't understand what you mean by "since we're already testing what it's doing", can you elaborate?

As far as I know we don't have any existing tests for this, which is why I put up this PR

**Comment by smrz2001** [comment]
> @smrz2001 I'm sorry, I don't understand what you mean by "since we're already testing what it's doing", can you elaborate?
> 
> As far as I know we don't have any existing tests for this, which is why I put up this PR

Oh ok, I misunderstood one of your Discord messages and thought that you realized after writing this test that this was already covered by existing tests. My bad.

**Review by smrz2001 — APPROVED** [review]
🚢

**Pull request merged**
