### PR TITLE
feat: add Stacks support

### PR DESCRIPTION
**Pull request by pradel**
## Description

As part of the [Sigle Grant](https://forum.ceramic.network/t/proposal-sigle-open-source-writing-platform-for-web3-content-creators/554), this pull request is creating the required components for Stacks to work with Ceramic.
The implementation is based on the work recently made to add Tezos support.

This pull request add the new Stacks verifier from the new `@didtools/pkh-stacks` created in the https://github.com/ceramicnetwork/js-did/pull/137. I am opening the pull request as a WIP for now and will update once the other pull request is merged and released.

Blockers:

- [x] Wait for https://github.com/ceramicnetwork/js-did/pull/137 to be merged and released

## How Has This Been Tested?

See https://github.com/ceramicnetwork/js-did/pull/137

## References:

Please list relevant documentation (e.g. tech specs, articles, related work etc.) relevant to this change, and note if the documentation has been updated.

### CODE REVIEW

**Review by zachferland — APPROVED** [review]

**Review by stbrody — APPROVED** [review]
seems fine to me.  FYI @oed

**Review by oed — APPROVED** [review]
Stacks uses `secp256k1` so should be fine. No external deps. 
@zachferland at some point it would be good to dedupe the use of multiple different signature libs in js-did.

**Comment by oed** [comment]
@pradel Looks like there's a conflict you need to fix
@zachferland I think this one is for you to merge after.

**Comment by pradel** [comment]
@oed conflict resolved 👍

**Comment by zachferland** [comment]
@stbrody can we have the tests run? or do we just merge?

**Comment by stbrody** [comment]
> @stbrody can we have the tests run? or do we just merge?

I don't think there's a way to force the tests on PRs from external contributors (@smrz2001?) but you can create your own PR with the same changes just to trigger CI, then if it passes merge this PR and close your duplicate PR

**Comment by smrz2001** [comment]
> > @stbrody can we have the tests run? or do we just merge?
> 
> I don't think there's a way to force the tests on PRs from external contributors (@smrz2001?) but you can create your own PR with the same changes just to trigger CI, then if it passes merge this PR and close your duplicate PR

Yeah, @zachferland, for now could you create a regular PR with changes from this PR?

@stbrody, I have an idea of how to fix this for external contributors and will take a look soon.

**Pull request merged**
