### PR TITLE
feat: Add env var to disable Data Feed

### PR DESCRIPTION
**Pull request by stbrody**

### CODE REVIEW

**Review by JulissaDantes — COMMENTED** [review]
Could you please provide the rationale for why we want to be able to disable the data feed?

**Comment by stbrody** [comment]
> Could you please provide the rationale for why we want to be able to disable the data feed?

We are seeing an OOM crash in js-ceramic and are trying to eliminate variables.  Data Feed is the newest big thing added to js-ceramic so if it was the cause it would explain why we never observed this OOM previously.

**Comment by stbrody** [comment]
Given that we seem to have discovered the source of the memory leak and it has nothing to do with DF, is this still worth adding or should we just close this PR without merging? @stephhuynh18

**Comment by stephhuynh18** [comment]
> Given that we seem to have discovered the source of the memory leak and it has nothing to do with DF, is this still worth adding or should we just close this PR without merging? @stephhuynh18

i think close makes sense

**Pull request closed without merging**
